version: 2
# Versão do arquivo de configuração do Dependabot

updates:
  - package-ecosystem: "pypi"
    # Ecosistema de pacotes que será atualizado, neste caso, PyPI
    
    directory: "/code" 
    # Diretório onde está localizado o arquivo requirements.txt
    
    schedule:
      interval: "weekly"
      # Intervalo para atualizações automáticas, neste caso, semanalmente
