name: Django CI

on:
  push:
    branches: [ "test/actions" ]
  pull_request:
    branches: [ "test/actions" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r code/requirements.txt
    - name: Run Tests
      run: |
        python code/manage.py makemigrations
        python code/manage.py migrate
        python code/manage.py test
