name: Django CI

on:
  push:
    branches: [ "test/actions" ]
  pull_request:
    branches: [ "test/actions" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd code
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd code
        python manage.py makemigrations admin accounts financas igreja
        python manage.py migrate admin accounts financas igreja      
        python manage.py test
