 name: Update NOTIFICATION v2
 on:
   push:
     branches:
       - teste/github-actions
   schedule:
     - cron: "0 * * * *"
 jobs:
   update_notification:
     runs-on: ubuntu-latest
     steps:
     - name: Install jq
       run: sudo apt-get install -y jq

     - name: Checkout
       uses: actions/checkout@v3
      
     - name: Use Node.js 14
       uses: actions/setup-node@v3
       with:
         node-version: '14'
        
     - name: Set up Git
       run: |
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
    
     - name: Pegar Issues
       run: |
         issue=$(curl --request GET \
         --url https://api.github.com/repos/maiconrp/AD-gestao/issues?state=open \
         --header "content-type: application/json" \
         --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}") | jq '.[] | .user.login + ": " + .title)
    
     - name: Pegar PRs
       run: |
         pullrequests=$(curl --request GET
          --url https://api.github.com/repos/maiconrp/AD-gestao/pulls
          --header "content-type: application/json"
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}") | jq '.[] | .user.login + ": " + .title')
     
     - name: Pegar Commits
       run: |
         commits=$(curl --request GET
          --url https://api.github.com/repos/maiconrp/AD-gestao/commits?state=open
          --header "content-type: application/json"
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}") | jq '.[] | .commit.author.name + ": " + .commit.message')
     
     - name: Monta template
       run:
         notification_template:="# Notificações\n\n### Issues:\n* **${issue}**\n\n\n### PRs:\n* **${pullrequests}**\n\n<hr>\n\n### Commits:\n* **${commits}:**" 
       
     - name: Update NOTIFICATION
       run: |
         printf ${notification_template} > NOTIFICATION.md
         git diff --quiet && echo "Nothing to commit" || git commit -am "🔧 Update NOTIFICATION with issues" && git push
