name: Update NOTIFICATION
on:
  push:
    branches:
      - teste/github-actions
  schedule:
    - cron: "0 * * * *"
jobs:
  update_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        
    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Get issues
      run: |
        $(curl --request GET \
        --url https://api.github.com/repos/maiconrp/AD-gestao/issues?state=open \
        --header "content-type: application/json" \
        --header "Accept: application/vnd.github+json" \
        --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}") > data.json
  
    - name: Update NOTIFICATION
      run: |
        echo $(echo "$(curl --request GET \
        --url https://api.github.com/repos/maiconrp/AD-gestao/issues?state=open \
        --header "content-type: application/json" \
        --header "Accept: application/vnd.github+json" \
        --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}")" | jq '.[] | {title: .title, authorID: .user.id}') >> NOTIFICATION.md
        echo ${{ steps.get_issues.outputs.issues }}
        git diff --quiet && echo "Nothing to commit" || git commit -am "🔧 Update NOTIFICATION with issues" && git push
