name: Update NOTIFICATION
on:
  push:
    branches:
      - teste/github-actions
  schedule:
    - cron: "0 * * * *"
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Get issues
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code} %{url_effective}\n" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/${{github.repository}}/issues?state=open)
        issues=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/${{github.repository}}/issues?state=open)
    - name: Print Issues
      run: echo "$issues"
    - name: Print Response
      run: echo "$response"
    - name: Pull changes
      run: git pull
    - name: Update NOTIFICATION
      run: |
        echo "$issues" >> NOTIFICATION.md
        git diff --quiet && echo "Nothing to commit" || git commit -am "🔧 Update README with issues" && git push
